### ISSUE TITLE
post no_signal.mem and project files

### ISSUE THREAD

**Issue by w531t4** [attie/led_matrix_tinyfpga_a2#1]
Could you please post no_signal.mem and any project file that would make it easy to import this into diamond or icecube?

**Comment by attie** [comment]
`no_signal.mem` can be generated from `no_signal.png` using the `convert.sh` script. If you'd still like me to commit this binary file, then please let me know (ideally I wouldn't).

I used Lattice Diamond for this project, the project file is `rgb_matrix.ldf`.

Please feel free to re-open if you need more.
