### ISSUE TITLE
64x64 Ledmatrix

### ISSUE THREAD

**Issue by B1tb0t** [attie/led_matrix_tinyfpga_a2#3]
Is it possible to port this code to support a 64x64 led matrix with A,B,C,D,E address lines ?

This is my exact model: https://www.alibaba.com/product-detail/SMD1515-dot-matrix-P2-RGB-LED_60808079124.html?spm=a2756.order-detail-ta-bn-b.0.0.4a842fc2fkABDD

My knowledge about FPGAs is really basic, but I want to build a simple driver for my matrix.
I think, your code would be perfect for my purpose.

**Comment by attie** [comment]
Yes, that should be fairly straight forward!... let me know how you get on.

If you're using the same part as I did, then the major issue will be with framebuffer memory... You'll probably need to reduce the color depth or figure something else out.

**Comment by B1tb0t** [comment]
Would the TinyFPGA BX in this case a better fit ? Or mabe the UPDuino v2.0 (http://www.gnarlygrey.com/) ? Moreover, are every led matrixes working with the TinyFPGA 3.3V logic (I thought they need 5V) ?

**Comment by B1tb0t** [comment]
@attie. Maybe this one would work as well: https://www.tindie.com/products/tinyvision_ai/upduino-v21-low-cost-fpga-board/ ?

**Comment by attie** [comment]
Yes, I think they would be okay... you're interested in either "_Block RAM_" or "_Distributed RAM_" for the framebuffer... if you're doing 16-bit per pixel (bpp), then the calculations would be:

    64 * 64 * 16 = 65,536 bits, or 8kBytes per frame buffer

Multiply that by two if you plan on double buffering.

Note also that sometimes the RAM is advertised as a certain size, but the full size may only be accessible in certain configurations / data widths...
